// This file is auto-generated by src/integrations/icons/utils/generate-icon-map.mjs.
// Do not edit manually. Run "npm run generate:icons" (or node src/integrations/icons/utils/generate-icon-map.mjs) to regenerate.

import type { IconType } from 'react-icons';
import { LuArrowRight, LuBookOpen, LuChevronRight, LuContact, LuGlobe, LuImage, LuMail, LuPhone, LuSettings } from 'react-icons/lu';
import { FaArrowLeft, FaArrowRight, FaArrowsUpDownLeftRight, FaBolt, FaBuilding, FaBullseye, FaClock, FaClockRotateLeft, FaComments, FaCompass, FaDroplet, FaEye, FaFeather, FaFileLines, FaHeadset, FaHouseFloodWater, FaLayerGroup, FaLifeRing, FaLink, FaPalette, FaPhone, FaRobot, FaRotateLeft, FaScaleBalanced, FaScrewdriverWrench, FaShieldHalved, FaShower, FaTemperatureArrowUp, FaThumbsUp, FaUniversalAccess, FaWandMagicSparkles, FaWater, FaWrench } from 'react-icons/fa6';
import { SiFacebook, SiInstagram, SiLinkedin } from 'react-icons/si';

export const iconMap = {
  'fa6:arrow-left': FaArrowLeft,
  'fa6:arrow-right': FaArrowRight,
  'fa6:arrows-up-down-left-right': FaArrowsUpDownLeftRight,
  'fa6:bolt': FaBolt,
  'fa6:building': FaBuilding,
  'fa6:bullseye': FaBullseye,
  'fa6:clock': FaClock,
  'fa6:clock-rotate-left': FaClockRotateLeft,
  'fa6:comments': FaComments,
  'fa6:compass': FaCompass,
  'fa6:droplet': FaDroplet,
  'fa6:eye': FaEye,
  'fa6:feather': FaFeather,
  'fa6:file-lines': FaFileLines,
  'fa6:headset': FaHeadset,
  'fa6:house-flood-water': FaHouseFloodWater,
  'fa6:layer-group': FaLayerGroup,
  'fa6:life-ring': FaLifeRing,
  'fa6:link': FaLink,
  'fa6:palette': FaPalette,
  'fa6:phone': FaPhone,
  'fa6:robot': FaRobot,
  'fa6:rotate-left': FaRotateLeft,
  'fa6:scale-balanced': FaScaleBalanced,
  'fa6:screwdriver-wrench': FaScrewdriverWrench,
  'fa6:shield-halved': FaShieldHalved,
  'fa6:shower': FaShower,
  'fa6:temperature-arrow-up': FaTemperatureArrowUp,
  'fa6:thumbs-up': FaThumbsUp,
  'fa6:universal-access': FaUniversalAccess,
  'fa6:wand-magic-sparkles': FaWandMagicSparkles,
  'fa6:water': FaWater,
  'fa6:wrench': FaWrench,
  'lu:arrow-right': LuArrowRight,
  'lu:book-open': LuBookOpen,
  'lu:chevron-right': LuChevronRight,
  'lu:contact': LuContact,
  'lu:globe': LuGlobe,
  'lu:image': LuImage,
  'lu:mail': LuMail,
  'lu:phone': LuPhone,
  'lu:settings': LuSettings,
  'si:facebook': SiFacebook,
  'si:instagram': SiInstagram,
  'si:linkedin': SiLinkedin,
} satisfies Record<string, IconType>;

export type IconKey = keyof typeof iconMap;
